### ISSUE TITLE
Html background image.

### ISSUE THREAD

**Issue by SurPun** [fac25/week2-markup-georgia-paz#10]
The image on the live page appears to be a background, maybe it will be better to use the [CSS property](https://www.w3schools.com/cssref/pr_background-image.asp)

**Comment by mariapaz** [comment]
Thanks Suraj, my idea was to add a srcset for this image. Large background images like this one tend to be too heavy for mobile devices. But after researching  I found 'img-set' that does the same as srcset but for bg images

https://dev.to/ingosteinke/responsive-background-images-with-image-set-the-srcset-for-background-image-259a

[It does need some prefix](https://caniuse.com/css-image-set)
